spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/cf-authuser
    username: postgres
    password: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
