server:
  port: 8087

spring:
  datasource:
    url:  ${DATABASE_URL:jdbc:postgresql://localhost:5432/cf-authuser}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
